// Generated by CoffeeScript 1.10.0
(function() {
  window.Phys = {};

  Phys.G = 6.67e-11;

  Phys.Celestial = function(x, y) {
    this.UUID = Util.UUID();
    this.X = x;
    this.Y = y;
    this.V = new Util.Vector2(0, 0);
    this.M = 5.972e24;
    this.R = 6.371e6;
    this.distanceTo = function(p) {
      var r;
      x = this.X - p.X;
      y = this.Y - p.Y;
      r = Math.sqrt(x * x + y * y);
      return r;
    };
    this.gVectorTo = function(p) {
      var g, gVector, r, theta;
      r = this.distanceTo(p);
      g = (Phys.G * p.M) / (r * r);
      theta = Math.atan2(y, x);
      gVector = new Util.Vector2(Math.cos(theta) * g, Math.sin(theta) * g);
      return gVector;
    };
    return this;
  };

  Phys.totalGravityVector = function(p, arr) {
    var ps, tgv, vs;
    ps = arr.filter(function(x) {
      return x !== p;
    });
    vs = ps.map(function(x) {
      return p.gVectorTo(x);
    });
    tgv = vs.reduce((function(a, v) {
      return a.add(v);
    }), new Util.Vector2(0, 0));
    return tgv;
  };

  Phys.checkCollisions = function(p, arr) {
    var cs, ps;
    ps = arr.filter(function(x) {
      return x !== p;
    });
    cs = ps.filter(function(x) {
      return x.distanceTo(p) <= x.R + p.R;
    });
    return cs;
  };

}).call(this);
