// Generated by CoffeeScript 1.10.0
(function() {
  window.Util = {};

  Util.Vector2 = function(x, y) {
    this.X = x;
    this.Y = y;
    this.add = function(v) {
      return new Util.Vector2(this.X + v.X, this.Y + v.Y);
    };
    this.scalar = function(s) {
      return new Util.Vector2(this.X * s, this.Y * s);
    };
    return this;
  };

  Util.ticksToMilliseconds = function(d) {
    return 1000 / d;
  };

  Util.UUID = function(a) {
    if (a) {
      return (a ^ Math.random() * 16 >> a / 4).toString(16);
    } else {
      return ([1e7] + -1e3 + -4e3 + -8e3 + -1e11).replace(/[018]/g, Util.UUID);
    }
  };

  Util.sizeCanvas = function() {
    var canvas;
    canvas = $('#screen')[0];
    canvas.style.width = '100%';
    canvas.style.height = '90%';
    canvas.width = canvas.offsetWidth;
    return canvas.height = canvas.offsetHeight;
  };

}).call(this);
