// Generated by CoffeeScript 1.10.0
(function() {
  window.Util = {};

  Util.Vector2 = function(x, y) {
    this.X = x;
    this.Y = y;
    this.add = function(v) {
      return new Util.Vector2(this.X + v.X, this.Y + v.Y);
    };
    this.scalar = function(s) {
      return new Util.Vector2(this.X * s, this.Y * s);
    };
    return this;
  };

  Util.ticksToMilliseconds = function(d) {
    return 1000 / d;
  };

  Util.sizeCanvas = function() {
    var canvas;
    canvas = $('#screen')[0];
    canvas.style.width = '100%';
    canvas.style.height = '90%';
    canvas.width = canvas.offsetWidth;
    return canvas.height = canvas.offsetHeight;
  };

}).call(this);
